input = "./EventLogs/Road_Traffic_Fine_Management_Process.xes.gz"
output = "outputs/complex_attribute_filter/"
compress_output = true

[pipeline]
seed = "0..2"

[[pipeline.mutations]]
type = "AttributeFilter"
target = "EventRequired"
key = "time:timestamp"
filter_method = { method = "DateBetween", value = [
	"2007-01-01T00:00:00Z",
	"2008-12-31T23:59:59Z"
]}

[[pipeline.mutations]]
type = "AttributeFilter"
target = "EventRequired"
key = "amount"
filter_method = { method = "FloatRange", value = [5,10]}

# Denoting filter_method as an inline table is equivalent to the following:
# [pipeline.mutations.filter_method]
# method = "FloatRange"
# value =[5, 10]

[[pipeline.mutations]]
type = "LogSplitter"
frac = 0.5
